apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test
  namespace: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      containers:
      - name: java-test
        image: 172.18.16.1:8083/java-test:1.0.35
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
